namespace ProjOb.Query
{
    public enum TokenType
    {
        Whitespace,
        Select,
        From,
        Where,
        Plus,
        Minus,
        Asterisk,
        Slash,
        Less,
        Greater,
        LessEqual,
        GreaterEqual,
        Equal,
        NotEqual,
        ConditionalAnd,
        ConditionalOr,
        ConditionalNegation,
        Identifier,
        Number,
        String,
        Separator,
        LeftParenthesis,
        RightParenthesis,
        EOS
    }
}
