namespace ProjOb.Query
{
    enum TokenType
    {
        Whitespace,
        Select,
        From,
        Where,
        Plus,
        Minus,
        Asterisk,
        Slash,
        Lower,
        Greater,
        LowerOrEqual,
        GreaterOrEqual,
        Equal,
        NotEqual,
        ConditionalAnd,
        ConditionalOr,
        ConditionalNegation,
        Identifier,
        Number,
        String,
        Separator,
        LeftParenthesis,
        RightParenthesis,
        EOS
    }
}
